name: Upload APK to Release

on:
  workflow_dispatch:
    inputs:
      file_name:
        description: "Release filename"
        required: true
      tag_name:
        description: "Release tag name"
        required: true

jobs:
  upload-apk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download APK artifact
        uses: actions/download-artifact@v3
        with:
          name: console-launcher-apk

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://api.github.com/repos/likeich/console-launcher/releases/tags/${{ github.event.inputs.tag_name }}
          asset_path: ./console-launcher-apk/${{ github.event.inputs.file_name }}
          asset_name: ${{ github.event.inputs.file_name }}
          asset_content_type: application/vnd.android.package-archive
